# Generated by Django 5.0.6 on 2024-06-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
