# Generated by Django 5.0.6 on 2024-06-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_post_number_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_number',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('board', '보안게시판'), ('news', '보안뉴스')], default='board', max_length=10),
        ),
    ]
