# Generated by Django 5.0.6 on 2024-06-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_post_post_number_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('board', '보안게시판'), ('news', '보안뉴스')], max_length=10),
        ),
    ]
