# Generated by Django 5.0.6 on 2024-07-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('temp1', '임시1'), ('temp2', '임시2'), ('temp3', '임시3'), ('temp4', '임시4')], max_length=10),
        ),
    ]
