# Generated by Django 5.0.6 on 2024-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0003_post_attachment_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('temp1', '보안뉴스'), ('temp2', '보안가이드'), ('temp3', '임시3'), ('temp4', '임시4')], max_length=10),
        ),
    ]
