# Generated by Django 5.0.6 on 2024-07-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0004_post_original_time_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('temp1', '보안뉴스'), ('temp2', '보안가이드'), ('temp3', '임시3'), ('temp4', '임시4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
