# Generated by Django 5.0.6 on 2024-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
